### ISSUE TITLE
小程序请求需https，博主什么时候更新，或者有什么办法能使正常访问？？？

### ISSUE THREAD

**Issue by vueCcc** [ahonn/weapp-one#3]

**Comment by qwlong** [comment]
在模拟器上不校验 ssl不就好了

**Comment by ljxyaly** [comment]
在微信开发者工具里面把这个“不校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书“选项勾选上了，还是没办法显示数据

**Comment by JinnTao** [comment]
var host = 'http://v3.wufazhuce.com:8000' 
这个已经被禁止了，没办法访问了

**Comment by JinnTao** [comment]
博主有有其他类似的办法吗?是不是需要自己搞一个啊？

**Comment by ahonn** [comment]
@JinnTao 自行解决，该项目已不再维护

**Comment by JinnTao** [comment]
= =求博主指导
